# Путь к файлу обученной модели
ckpt_path: "model_weights/weights.pt"

# Частота дискретизации аудио, на которой обучалась модель
sample_rate: 16000

# Размер одного промежутка аудио для обработки (в миллисекундах).
# Этот размер должен совпадать с размером, на котором обучалась модель
chunk_size: 1000

# Шаг (в миллисекундах), который будет совершаться после каждого промежутка
stride: 1000

# Флаг, указывающий, следует ли усреднять предсказания модели для 
# накладывающихся сегментов (наложения происходят, когда stride < chunk_size).
# Повышает точность предсказаний за счет увеличенного времени обработки
mean_overlaps: False

# Пороговое значение срабатывания модели (в интервале от 0 до 1).
# Чем выше это значение, тем "строже" модель 
# по отношению к ключевому (последнему) классу
threshold: 0.25

# Флаг, указывающий, следует ли включать предсказанные 
# вероятности каждого класса в файл меток
include_probs: True

# Путь для сохранения файла разметки
label_path: "output"

# Путь для сохранения сгенерированного "чистого" аудио 
# (только с интервалами храпа)
clear_audio_path: "clear_audio"

# Название "чистого" аудио
# может быть не указано (аудио не будет сохранено)
generate_clear_audio: "jit_model"

# Размер пакета во время обработки
batch_size: 128