general:
  model_name: "SAD_M5E_kaggle_test"
  description: 

  device: "cuda"
  cuda_params:
    pin_memory: True
    num_workers: 6
    persistent_workers: True

  # add mixed precision training
  save_only_best: True
  convert_to_fp16: 

  continue_from:  # with original fc layer

  finetune_from:  # with new fc layer
  # restore_scheduler_state: True

  seed: 1234

  export_path: "D:/exported_snore_models"


training:
  model_to_use: "CB"  # docs ; multiple models

  dataset_path: "D:/SnoreFeatures_kaggle"  # doesn't work if "prepare_dataset_conf" is specified

  epochs: 20

  # add more loss funcs
  loss_func:
    type: "crossentropy"
    params:
      label_smoothing: 0

  optimizer:
    type: "adamw"  # adamw
    params:
      lr: 0.001
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: !!float 1e-08
      amsgrad: False
    # warmup: False
  
  # add scheduler

  
models_params:
  M5:
    n_channel: 40
    stride: 16

  M5E:
    n_channel: 40
    stride: 16
  
  CB:
    ffn_dim: 64
    lstm_dim: 32

  # write conf for other models