general:
  model_name: "snore_model"
  description: "this is snore detection model"

  device: "cpu"
  cuda_params:
    pin_memory: True
    num_workers: 6
    persistent_workers: True

  save_only_best: True
  seed: 1234

  export_path: "C:/exported_snore_models"


training:
  model_to_use: "M5E"

  dataset_path: "C:/features_save_dir"

  epochs: 20

  loss_func:
    type: "crossentropy"
    params:
      label_smoothing: 0

  optimizer:
    type: "adam"
    params:
      lr: 0.001
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: !!float 1e-08
      amsgrad: False  

  
models_params:
  M5:
    n_channel: 40
    stride: 16

  M5E:
    n_channel: 40
    stride: 16
  
  CB:
    ffn_dim: 64
    lstm_dim: 32

  CA:
    transformer_nhead: 4
    transformer_dropout: 0.2
    ffn_dim: 256
