SNORE_TAG = "SNORE"
NO_SNORE_TAG = "NO_SNORE"
HOME_TAG = "HOME"
HUMAN_TAG = "HUMAN"

DATASET_CSV_URL = "http://storage.googleapis.com/us_audioset/youtube_corpus/v1/csv/unbalanced_train_segments.csv"

# https://github.com/audioset/ontology/blob/master/ontology.json
AUDIO_LABELS = {
    "/m/01d3sd": "Snore",
    "/m/02dgv": "Door",
    "/m/0642b4": "Cupboard open or close",
    "/m/0fqfqc": "Drawer open or close",
    "/m/04brg2": "Dishes, pots, and pans",
    "/m/023pjk": "Cutlery, silverware",
    "/m/07pn_8q": "Chopping (food)",
    "/m/0dxrf": "Frying (food)",
    "/m/0fx9l": "Microwave oven",
    "/m/02pjr4": "Blender",
    "/g/11b630rrvh": "Kettle whistle",
    "/m/02jz0l": "Water tap, faucet",
    "/m/0130jx": "Sink (filling or washing)",
    "/m/03dnzn": "Bathtub (filling or washing)",
    "/m/03wvsk": "Hair dryer",
    "/m/01jt3m": "Toilet flush",
    "/m/012xff": "Toothbrush",
    "/m/0d31p": "Vacuum cleaner",
    "/m/01s0vc": "Zipper (clothing)",
    "/m/0zmy2j9": "Velcro, hook and loop fastener",
    "/m/03v3yw": "Keys jangling",
    "/m/0242l": "Coin (dropping)",
    "/m/05mxj0q": "Packing tape, duct tape",
    "/m/01lsmm": "Scissors",
    "/m/081rb": "Writing",
    "/m/02g901": "Electric shaver, electric razor",
    "/m/05rj2": "Shuffling cards",
    "/m/0316dw": "Typing",
    "/m/0lyf6": "Breathing",
    "/m/07mzm6": "Wheeze",
    "/m/07s0dtb": "Gasp",
    "/m/07pyy8b": "Pant",
    "/m/07q0yl5": "Snort",
    "/m/01b_21": "Cough",
    "/m/0dl9sf8": "Throat clearing",
    "/m/01hsr_": "Sneeze",
    "/m/07ppn3j": "Sniff",
}

LABEL_MAPPING = {
    "Door": HOME_TAG,
    "Cupboard open or close": HOME_TAG,
    "Drawer open or close": HOME_TAG,
    "Dishes, pots, and pans": HOME_TAG,
    "Cutlery, silverware": HOME_TAG,
    "Chopping (food)": HOME_TAG,
    "Frying (food)": HOME_TAG,
    "Microwave oven": HOME_TAG,
    "Blender": HOME_TAG,
    "Kettle whistle": HOME_TAG,
    "Water tap, faucet": HOME_TAG,
    "Sink (filling or washing)": HOME_TAG,
    "Bathtub (filling or washing)": HOME_TAG,
    "Hair dryer": HOME_TAG,
    "Toilet flush": HOME_TAG,
    "Toothbrush": HOME_TAG,
    "Vacuum cleaner": HOME_TAG,
    "Zipper (clothing)": HOME_TAG,
    "Velcro, hook and loop fastener": HOME_TAG,
    "Keys jangling": HOME_TAG,
    "Coin (dropping)": HOME_TAG,
    "Packing tape, duct tape": HOME_TAG,
    "Scissors": HOME_TAG,
    "Writing": HOME_TAG,
    "Electric shaver, electric razor": HOME_TAG,
    "Shuffling cards": HOME_TAG,
    "Typing": HOME_TAG,
    "Breathing": HUMAN_TAG,
    "Wheeze": HUMAN_TAG,
    "Gasp": HUMAN_TAG,
    "Pant": HUMAN_TAG,
    "Snort": HUMAN_TAG,
    "Cough": HUMAN_TAG,
    "Throat clearing": HUMAN_TAG,
    "Sneeze": HUMAN_TAG,
    "Sniff": HUMAN_TAG,
    "Snore": SNORE_TAG,
}

YT_VIDEO_URL = "https://www.youtube.com/watch?v="