general:
  training_tokens: ["NO_SPEECH", "SPEECH", "SNORE"]

  limit_for_class: "SNORE"
  # limit_for_class: 22000

  chunk_size: 1000
  stride: 128
  sample_rate: 16000

  feature_type: "raw"

  win_len: 10
  n_fft: 256
  hop_len: 10
  n_mels: 32
  
  compute_threads: 8
  use_gpu: False

  batch_size: 32
  shuffle_window: 100
  shuffle_hop: 10

  output_path: "D:/SnoreFeatures_kaggle"
  train_val_split: [85, 10]
  train_folder: "train"
  val_folder: "validation"
  test_folder: "test"

  use_equalization: -20

  # use_silence:
  #   ratio: 0.3
  #   silence_path: "C:/Users/shace/Documents/GitHub/snore_detector/SnoreActivityDetector/audio_data/mic_noise_examples"
  #   augmentations: ["gaussian_noise", "background_noise"]

  # labels_merging:
  #   "SPEECH": "NO_SNORE"
  #   "NO_SPEECH": "NO_SNORE"
  #   "SNORE": "TTTSNORE"

  augmentations_config:
    background_noise:
      noise_path: "C:/Users/shace/Documents/GitHub/snore_detector/SnoreActivityDetector/audio_data/sound_noises"
      level: [0.05, 0.3]
      probability: 0.25
    gaussian_noise:
      level: [0.0005, 0.00005]
      probability: 0.3
    random_gain:
      min_gain: -25.0
      max_gain: 1.0
      probability: 0.5
    time_shift:
      shift_factor: [0.1, 0.3]
      probability: 0.15
    impulse:
      impulse_path: "C:/Users/shace/Desktop/hey-terra-kws-2-tf/nano-kws/impulses/h017_Livingroom_152txts_16bit.wav"
      level: [0.5, 0.8]
      probability: 0.2
    low_pass_filter:
      max_cutoff_freq: 8000
      min_cutoff_freq: 1500
      probability: 0.2


data_kaggle:
  path: "C:/Users/shace/Documents/GitHub/snore_detector/SnoreActivityDetector/audio_data/kaggle_snore2"
  tokens: ["SNORE"]
  augmentations: [[]]


speech:
  path: "D:/full_ava_dataset"
  label_file: "label.json"
  audio_folder: "audios"
  tokens: ["NO_SPEECH", "SPEECH"]
  augmentations: [[], []]